### ISSUE TITLE
Feedback from additional reviewer

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-rest-client-angularjs#10]
Copying here from private Slack discussion:

1) Starting the service section has `cd start` which isn’t necessary as the previous instruction to `cd guide-rest-client-angularjs/start` puts you in that directory already.

2) The ‘copy’ icon is tempermental. It should appear all the time rather than randomly appearing - I can’t get it to appear on the ‘Starting the service’ code snippet (edited)
 
3) A small gotcha with the copy icon is that the final line doesn’t have a newline associated with it when you paste into a terminal window. If there was an additional newline then all the commands would be tee’d up to run

4) http://localhost:9080/artists should be a hyperlink … omg http text in web sites that aren’t links are SOOOOO annoying

5) ‘Create the AngularJS controller’ is a little clumsy in its wording here:

![image](https://user-images.githubusercontent.com/3322532/33177248-ddbba51c-d059-11e7-92e6-d7f3608d8fd4.png)

Specifically, it isn't really clear what 'the definition' is that is referred to. I think the paragraph before the snippet just needs rewording more clearly. And, although the full path of the .js file is given in a standard way before the code snippet, it doesn't really make sense to do that here (especially having two consecutive colons (:) before the snippet).

6) the index.html in start/… already contains a `<head>` … need to say to replace it

7) in the section where the `<body>` is constructed, it’s built up over 3 stages. It’s not clear that you shouldn’t copy/paste each section as you go. The correct thing is to read the whole section, and copy-paste the code snippet in the last section. So the ‘copy’ icon shouldn’t appear in the first two snippets in that section. - Maybe an icon that means  ‘don’t copy this section yet … read on’

8.
> After everything is set up, point your browser to the application root localhost:9080 to see the following output:

this could be a link as well: http://localhost:9080 … I guess I was just refreshing the link I was told to go to above and wasn’t getting anything useful (maybe just me being rushed / lazy)

**Comment by yeekangc** [comment]
Item 7 is an issue that I have discussed with @Kubik42.  We should improve upon what we have.

**Comment by lauracowen** [comment]
I'm just fixing up #1-4 but have to do something else so I'm going to create a PR of what I've done so far to avoid holding it up.

**Comment by lauracowen** [comment]
Created PR for items 1-4.

Adding some more explanation for item 6 to the original post above.
