### ISSUE TITLE
Minor issues for guide

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-rest-client-angularjs#3]
- Duplication or typo with "... see Creating a RESTful web service. Creating a RESTful web service."

- Clarify that users need to create this file: start/src/main/webapp/js/consume-rest.js

- Clarify where/what is the application root and what we should do for "If everything was set up correctly, the following will be displayed at the application root:"

**Comment by Kubik42** [comment]
Everything addressed in #5
