### ISSUE TITLE
No automated tests for AngularJS guide

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-rest-client-angularjs#31]
We need to add automated tests so they can be ran automatically, at least for regression purpose.  The provided endpoints should at least be tested.

**Comment by justineechen** [comment]
The provided endpoint is tested through the .travis.yml file now in the multipane branch. 
https://github.com/OpenLiberty/guide-rest-client-angularjs/blob/multiPane/.travis.yml

We've looked into making tests to verify the angularjs controller specifically but have decided not to add that to the guide as of now. @gkwan-ibm

**Comment by evelinec** [comment]
The endpoint test is now running in daily build tests as well via #48.

**Comment by DannyS03** [comment]
Guide is running automated tests.
