### ISSUE TITLE
Multipane issues

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-rest-client-angularjs#34]
- [x] Edit [empty html] file from start, to Create file 

- [x] Hyperlink AngularJS page 

- [x] Parent pom update 

- [x] Travis -q flag

- [x] No surefire/failsafe plugins

**Comment by Rachelwrq** [comment]
### Checklist for multipane conversion
**Through the browser:**
- [ ] Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] Test the actual application (use it, hit endpoints, etc.)
- [ ] No files in the middle panel (guide section)
- [ ] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [x] Make sure hotspots actually point to the correct lines
- [x] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [x] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [x] Guide attribution is present

**In the README.adoc:**
- [x] Tags in the front matter are correct
     - [x] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [x] Failsafe plugin and Surefire plugin updates if applicable
- [x] Parent POM update
     - [x] start directory
     - [x] finish directory
- [ ] Files are formatted correctly
- [x] .travis.yaml file is updated accordingly

**Comment by Erikkre** [comment]
### Checklist for Review
**Through the browser:**
- [ ] Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] Test the actual application (use it, hit endpoints, etc.)
- [ ] No files in the middle panel (guide section)
- [ ] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [ ] Make sure hotspots actually point to the correct lines
- [ ] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [ ] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [ ] Guide attribution is present
- [ ] Any links are hyperlinks with the webpage title not the URL
- [ ] Feature versions should not be included in the guide
**In the README.adoc:**
- [ ] Tags in the front matter are correct (MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE)
    - [ ] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [ ] Failsafe plugin and Surefire plugin updates if applicable
- [ ] Parent POM update
    - [ ] start directory
    - [ ] finish directory
- [ ] Files are formatted correctly
- [ ] .travis.yaml file is updated accordingly

I also think artist should be changed to artists since that is what it is in the code, and $resource should have a hotspot.

**Comment by justineechen** [comment]
- Updated artist to artists
- I don't think $resource should be hot spotted in the first section because we're referencing it at a higher level before the user knows anything about the guide, $resource is hot spotted in later sections when it's more relevant to the code

**Comment by andrewdes** [comment]
- [ ] All the code commands have `start/` included in them
- [ ] "You will implement an AngularJS client that consumes this JSON and displays its contents at the following URL: http://localhost:9080" -> No period at the end of the sentence
- [ ] "After you start the server, you can find your artist JSON at the following URL: http://localhost:9080/artists" -> No period at the end of the sentence
- [ ] "Target the artist JSON URL in the `$resource()` call." -> `$resource()` should be hotspotted
- [ ] "The `controller` controls the..." -> `controller` hotspot is wrong
- [ ] "You can now access the `artists` property from..." -> `artists` should be hotspotted
- [ ] "You will create the starting point of your application under start/src/main/webapp/index.html" -> Is this sentence necessary? The path is stated in the code command under this sentence.
- [ ] "The second library is responsible for providing the APIs for the `$resource` service." -> Should `$resource` be hotspotted?
- [ ] "... attached to the `body` of the template." -> I think `body` should be hotspotted
- [ ] "This will make the artists property of the $scope object available to access at the point in the DOM where the controller is attached:" -> I think `$scope` and `artists` should be hotspotted. Also why does this sentence end in a colon?
- [ ] "using the `{{ artists }}` expression." -> should be hotspotted. Same with the "`artists` property" before and after this sentence
- [ ] "Consuming a RESTful web service with AngularJS by {guide-author} is licensed under CC BY-ND 4.0" -> Need to add `guide-author` to front-matter




- [ ] I think lots of paragraphs in this guide can be combined. I am assuming they used to be separated by sections of code? However, now with multipane it doesn't make sense for them to be separate paragraphs. I.e. In the **Creating the AngularJS template**:

> Next, the ArtistCtrl controller is attached to the DOM to create a new child scope.
> 
> This will make the artists property of the $scope object available to access at the point in the DOM where the controller is attached:

**Comment by justineechen** [comment]
- "This guide isn't consistent with the others that tell users to navigate to the start directory to begin", Users run the guide from the start directory so they are already there before they need to create the file. I'm going to add cd start before mvn install.. etc. though

**Comment by justineechen** [comment]
2nd round:
- [ ] guide author
- [ ] update to master
- [ ] mvn instructions
- [ ] if there is a clean comment, let consider or discuss it
- [ ] make sure liberty:stop-server before the testing (assumed testing is at the end)

**Comment by andrewdes** [comment]
@justineechen the guides do not use the command `cd start`, they instead tell users to "Navigate to the `start` directory to begin" or similar.

**Comment by justineechen** [comment]
- [ ] Git clone on the right panel isn't showing up on this guide 
- [ ] There are two gray boxes on the `index.html` file that shouldn't be there https://github.com/OpenLiberty/openliberty.io/issues/902

**Comment by justineechen** [comment]
This guide has successfully been converted to multipane and has no blockers.
