### ISSUE TITLE
multipane issue

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-rest-client-angularjs#38]
- [x] at the "Starting the service" section, remove the following paragraph because the guide do not want to stop the server. Instead, should ask reader to stop the server at the end of the "Testing the AngularJS client" section

    - "When you are done checking out the services, stop the Open Liberty server by running the following command: 'mvn liberty:stop-server`"

**Comment by justineechen** [comment]
Updated "Testing the AngularJS client" section to:
```
Whenever you change your AngularJS implementation, the application root at http://localhost:9080[http://localhost:9080^] will
reflect the changes automatically. You can visit the root to manually check whether the artist JSON
was consumed correctly.

When you are done checking the application root, stop the Open Liberty server by running the following command:
[role='command']

mvn liberty:stop-server
```
