### ISSUE TITLE
Improve "Creating the AngularJS Template"

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-rest-client-angularjs#4]
- Clarify that the <head> and <body> provided in the starter index.xml shall be overwritten or replaced;

- The code snippets build on top of each other and there are overlaps making it more difficult for users that will copy and paste.  Should avoid overlap so users can copy and paste without needing to delete/clean up duplicate code;

- Make clear that ```<script src='./js/consume-rest.js'></script>``` should be appended and should not overwrite the previous 2 imports added.

**Comment by Kubik42** [comment]
Points 1 and 3 addressed in #5. As for point 2, there are only three code snippets that do this and the first two are very short. I believe its better this way since the snippets show what is supposed build on top of what.

**Comment by yeekangc** [comment]
What we can consider is to take away `<head>` and `<body>` from the copy blocks and explain that users should append or update those stanzas.

**Comment by yeekangc** [comment]
The point being coming up with a flow that will make it users to go through the guide easily (without hassle) if they will directly copy and paste.

I am not sure if the change for point 3 addressed this either.

**Comment by Kubik42** [comment]
Ok, I've merged point 3 into a single snippet since both blocks look almost similar and users may seem confused at first why the blocks are repeating.

**Comment by yeekangc** [comment]
Great.  Good with that and we can noodle on the second issue.

**Comment by Kubik42** [comment]
Fixed in #12
