### ISSUE TITLE
Need to fix daily build test after dev mode

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-rest-client-angularjs#60]
Recent test shows success, but it is not running with the correct daily build: https://travis-ci.org/OpenLiberty/guide-rest-client-angularjs/builds/620051994

**Comment by evelinec** [comment]
@NimG98 can you fix this one together with the openapi guide? I think they'd be the same issue. Thanks.

**Comment by NimG98** [comment]
Daily build PR has been merged, will verify tmrw morning if it's running correctly.

**Comment by NimG98** [comment]
Daily build test is passing now, and `<install>` tag is being correctly placed in LMP plugin.

https://travis-ci.org/OpenLiberty/guide-rest-client-angularjs/jobs/621090806#L253

**Comment by evelinec** [comment]
Looks good. Closed.
